github:
  description: Apache Pinot Website
  homepage: https://pinot.apache.org/
  labels:
    - pinot
    - website
  features:
    wiki: true
    issues: true
    projects: true
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
  protected_branches:
    new-site-dev:
      required_status_checks:
        strict: false
